data:
  img_shape: (64, 64)
  num_workers: 0

model:
  n_frames: 8
  n_feature_maps: 32
  feature_map_width: 16
  feature_map_height: 16
  feature_map_gauss_sigma: 1.5
  n_init_filters: 32
  n_convolutions_per_res: 1  # Convolutions per scale
  conv_kernel_size: 3
  decoder_hidden_activations: LeakyReLU
  encoder_hidden_activations: LeakyReLU
  weight_init: he_normal

training:
  k_folds: 0
  epochs: 200
  steps_per_epoch: 200
  optim: Adam
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_epoch_steps: 10
  lr_scheduler_gamma: 0.9
  initial_lr: 0.0001
  max_lr: 0.001
  min_lr: 0.0001
  clip_norm: 1.0
  batch_size: 2
  l2_weight_decay: 0.00005  # Conv.-kernel regularization
  reconstruction_loss: sse
  reconstruction_loss_scale: 0.1
  feature_map_regularization: 5.0  # Key-point sparsity scale
  separation_loss_scale: 0.1
  separation_loss_sigma: 0.02
  patchwise_contrastive_scale: 1.0
  patchwise_contrastive_starting_epoch: 0
  patchwise_contrastive_type: patch
  patchwise_contrastive_time_window: 3
  patchwise_contrastive_patch_size: (7, 7)
  patchwise_contrastive_alpha: 0.5
  use_emd: false
  emd_sum_scale: 1.0
  re_sample: false
  re_sample_scale: 0.02

validation:
  steps: 50
  freq: 5
  batch_size: 2  # 32
  save_video: true

evaluation:
  steps: -1

device: cuda:0
multi_gpu: false
log_dir: "results/pacolo/pacolo_acrobot_new_64pix"
warm_start: false
warm_start_checkpoint: ''
warm_start_config: ''