data:
  num_workers: 4
  img_shape: (3, 128, 128)

model:
  n_frames: 8
  hidden_dim: 32
  num_img_channels: 3
  num_keypoints: 8
  activation: LeakyReLU
  gaussian_map_std: 0.05
  weight_init: he_normal
  skip_connections: False

training:
  epochs: 300
  steps_per_epoch: 500
  optim: Adam
  k_folds: 0
  initial_lr: 0.0005  # 0.001
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_epoch_steps: 10
  lr_scheduler_gamma: 0.9
  batch_size: 8
  loss_function: sse
  l2_weight_decay: 0.00005
  grad_clip_max_norm: 1.0

validation:
  steps: 50
  freq: 5
  batch_size: 8
  save_grad_plots: False  # True
  save_eval_examples: False  # True

evaluation:

device: cuda:0
log_dir: 'results/transporter/transporter_vssil_new_128pix'
warm_start: True
warm_start_config: '//home/yannik/vssil/results/transporter/transporter_vssil_new_128pix/2022_3_1_13_53_resume/config.yml'
warm_start_checkpoint: '/home/yannik/vssil/results/transporter/transporter_vssil_new_128pix/2022_3_1_13_53_resume/checkpoints/chckpt_f0_e290.PTH'